[[redirects]]
from = "http://photos.cao.sh/*"
to = "https://cao.sh/photos/:splat"
status = 301
force = true

[[redirects]]
from = "https://photos.cao.sh/*"
to = "https://cao.sh/photos/:splat"
status = 301
force = true

[[redirects]]
from = "http://www.cao.sh/*"
to = "https://cao.sh/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.cao.sh/*"
to = "https://cao.sh/:splat"
status = 301
force = true
